markup:
  goldmark:
    renderer:
      unsafe: true
baseURL: 
languageCode: en-us
build:
  writeStats: true
params:
  title: Abrar CV
  author: 
  description: Website title
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Mahboob Abrar Ali Syed"
    tagline: 
    location: "Hamburg, Germany"
    photo: bild2.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/syed-abrar-ali/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/Abrar-04"
        title: GitHub
      - icon: ai ai-google-scholar
        url: "https://scholar.google.com/citations?user=8cp2KiMAAAAJ&hl=en"
        title: Google Scholar
  showInAccordion:
    - item: aboutme
      expand: true
    - item: education
    - item: experience
    - item: publication
    - item: project
    - item: Skills
    - item: hobby

  aboutme:
    title: About Me
    icon: fas fa-user
    description: A dedicated professional with a passion for problem solving with data-driven decision-making for user-centered
                solutions. Motivated and eager to learn, thrive in collaborative environments, and make valuable contributions to
                the modern day industry and to work towards a better future.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: MSc Data Science
        college: Technische Universität Hamburg
        dates: 2024 - Present
      - degree: BE Computer Science and Engineering
        college: Osmania University
        dates: 2018 -2022
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Analyst
        company: Deloitte Consulting
        dates: Jan 2023 - Sept 2024
        details: |1-
          - Implemented robust error-handling mechanisms and bulk processing techniques to ensure the reliability and
            scalability of custom Apex solutions and optimization of complex Apex triggers and classes to automate
            business processes, resulting in a 30% increase in operational efficiency.
          - Contributed to development of LWCs by optimizing healthcare workflows and enhancing the overall User
            Interface and Experience. Achieved a 25% improvement in component load times, delivering a more responsive
            and modern experience for critical healthcare system end users.
          - Designed Interactive Reports and Dashboards to provide actionable insights on patient care metrics, trends
            and other Healthcare KPIs, improving overall decision-making processes for stakeholders.
          - Collaborated with clients and cross-functional teams and implemented regular code reviews, assisted in
            Proof-of-Concept Ideations, Business-side presentations and demos.
      - position: Machine Learning Engineer
        dates: Jul 2012 - Dec 2022
        company: Freelance
        details: |1-
          - Developed an image-based AI pipeline to detect and segment
            individuals from group images, predicting their age and gender
            using deep learning models. 
          - Trained and fine-tuned YOLOv5 to detect and classify clothing
            items (topwear, bottomwear, footwear) while implementing
            background segmentation to enhance object recognition and
            improve downstream processing. 
          - Implemented a color analysis and feature embedding system by
            extracting the top three dominant colors from clothing items
            and generating TensorFlow embeddings, enabling content
            based recommendations for fashion applications. 
  
  publication:
    title: Publications
    icon: fas fa-book
    list:
      - title: IEEE Xplore
        url: "https://ieeexplore.ieee.org/abstract/document/9497809"
        paper: Early Detection of Malpositioned Catheters and Lines on Chest X-Rays using Deep Learning
        journal: "International Conference on Artificial Intelligence and
                  Computer Science Technology - 2021, Indonesia"

  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Dr.Detect
        url: "https://github.com/MSufiyanAG/dr_detect"
        details: |1-
          - Designed and Developed a Web Application for early diagnosis of reports of 6 medical conditions by detecting
            and classifying abnormalities based on severity even in the absence of a medical specialist.
          - Data collected from reputed medical sources and trained over State-of-the-Art architectures (UNet,DenseNet)
          - Conducted Data & Feature Engineering and Deployed the application on Azure to ensure realiability.
          - Conducted Surveys to refine the app's user interface and enhance the user experience. 
      - title: Swachh-Companion
        url: "https://github.com/syedwajid01/Swachh-Companion"
        details: |1-
          - Built a Mobile Application to assist in waste segregation into biodegradable and non-biodegradable categories
          - Collected, processed, and analyzed image data to improve classification accuracy by training and optimizing
            the MobileNet model. Deployed using TensorFlow Lite for faster real-time inference.
          - Included a feature to connect volunteers seeking to help NGOS in fostering community engagement in
            recycling and cleaning for a better cause.
  Skills:
    title: Skills
    icon: fas fa-cogs
    list:
      - title: Languages 
        description: |1-
          -  Python, R, JavaScript, Java, SQL
      - title: Developer Tools 
        description: |1-
          -  PowerBI, Tableau, Docker, Salesforce Development [Apex, LWC], Jupyter Notebooks, Microsoft Office Suite
      - title: Technologies/Frameworks
        description: |1-
          -  Linux, Git, Sklearn, Numpy, Pandas, Matplotlib, PyTorch, TensorFlow, OpenCV
      - title: Soft skills
        description: |1-
          -  User Research, Journey Mapping, Design Thinking, Business Intelligence

  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Gaming
      - hobby: Sports
      - hobby: Sketching
      - hobby: Cooking

